# How to Download NFIP Datasets from OpenFEMA
Author: Mark Bauer

In [1]:
# import libraries
import logging
from datetime import datetime
from urllib.parse import urlencode
import requests
import duckdb
import pandas as pd
import os
import json
import tempfile
import os
import time

In [2]:
# reproducibility
%reload_ext watermark
%watermark -v -p requests,duckdb,pandas

Python implementation: CPython
Python version       : 3.11.0
IPython version      : 8.6.0

requests: 2.28.1
duckdb  : 1.0.0
pandas  : 1.5.1

In [3]:
# data retrieved, not to be confused with data of data
current_date = datetime.now()
print(f"The data was retrieved on {current_date.strftime('%Y-%m-%d')}.")

The data was retrieved on 2025-07-02.

# Overview
This notebook demonstrates how to download and work with the National Flood Insurance Program (NFIP) [datasets](https://www.fema.gov/about/openfema/data-sets#nfip) from [OpenFEMA](https://www.fema.gov/about/reports-and-data/openfema). The workflows are designed to be efficient, easy to adapt, and easy to understand. These examples also include brief data exploration using [DuckDB](https://duckdb.org/).

## Datasets
- [FIMA NFIP Redacted Claims - v2](https://www.fema.gov/openfema-data-page/fima-nfip-redacted-claims-v2)
- [FIMA NFIP Redacted Policies - v2](https://www.fema.gov/openfema-data-page/fima-nfip-redacted-policies-v2)
- [NFIP Multiple Loss Properties - v1](https://www.fema.gov/openfema-data-page/nfip-multiple-loss-properties-v1)
- [NFIP Residential Penetration Rates - v1](https://www.fema.gov/openfema-data-page/nfip-residential-penetration-rates-v1)
- [2023 NFIP Reinsurance Placement Information](https://www.fema.gov/about/openfema/data-sets/national-flood-insurance-program-nfip-reinsurance-placement-information)
- [NFIP Community Layer Comprehensive - v1](https://www.fema.gov/openfema-data-page/nfip-community-layer-comprehensive-v1)
- [NFIP Community Layer No Overlaps Split - v1](https://www.fema.gov/openfema-data-page/nfip-community-layer-no-overlaps-split-v1)
- [NFIP Community Layer No Overlaps Whole - v1](https://www.fema.gov/openfema-data-page/nfip-community-layer-no-overlaps-whole-v1)
- [NFIP Community Status Book - v1](https://www.fema.gov/openfema-data-page/nfip-community-status-book-v1)

## Notes
- Datasets are downloaded in Parquet format whenever possible for performance and compatibility.
- DuckDB is used for querying and previewing the data.
- The NFIP Community Layers dataset is large and has been excluded from this repository (tracked via .gitignore), but other datasets are included both locally and on GitHub.
- For the NFIP Policies and Claims datasets, the current focus is on a sample of New York City.

## Disclaimer
This analysis uses the Federal Emergency Management Agency’s OpenFEMA API, but is not endorsed by FEMA. The Federal Government or FEMA cannot vouch for the data or analyses derived from these data after the data have been retrieved from the Agency's website(s).

Read more about OpenFEMA's [Terms and Conditions](https://www.fema.gov/about/openfema/terms-conditions).

# Getting Started: Dataset Metadata
Before we get started, let's review the metadata for each dataset. Luckily, the OpenFEMA API has a great endpoint for this, `OpenFemaDataSets`.

In [4]:
url = (
    "https://www.fema.gov/api/open/v1/OpenFemaDataSets"
    "?$filter=theme eq 'National Flood Insurance Program'"
)

response = requests.get(url)

if response.ok:
    data = response.json()
    metadata_df = pd.DataFrame(data['OpenFemaDataSets'])
else:
    print(f"Failed to download data. Status code: {response.status_code}")
    
# preview data    
print(metadata_df.shape)    
metadata_df

(8, 39)

,identifier,name,title,description,webService,dataDictionary,keyword,modified,publisher,contactPoint,...,recordCount,depDate,depApiMessage,depWebMessage,depNewURL,hash,lastRefresh,id,lastDataSetRefresh,distribution
0,openfema-39,NfipCommunityStatusBook,NFIP Community Status Book,The National Flood Insurance Program (NFIP) en...,https://www.fema.gov/api/open/v1/NfipCommunity...,https://www.fema.gov/openfema-data-page/nfip-c...,"[NFIP, Status Book, Community Status Book, Flo...",2024-11-07T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,...,25053,None,None,None,None,7b8f6d05763d0c656c524c44438e1d8e8552abe8,2024-11-21T14:40:15.168Z,edccafe8-40f9-472a-84a9-e7cbbab850e2,2025-07-03T03:14:05.889Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
1,openfema-86,NfipResidentialPenetrationRates,NFIP Residential Penetration Rates,"NFIP ""take-up rates"" or residential penetratio...",https://www.fema.gov/api/open/v1/NfipResidenti...,https://www.fema.gov/openfema-data-page/nfip-r...,"[nfip, rates, nsi, residential structures, pol...",2024-11-07T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,...,3162,None,None,None,None,c84151b7bbe46b75c5143a0c9d491a9986247f06,2024-11-21T14:40:15.168Z,18f6002e-40a5-4601-9504-279b8e6bf985,2025-05-19T15:20:16.607Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
2,openfema-78,NfipMultipleLossProperties,NFIP Multiple Loss Properties,This dataset provides information on structure...,https://www.fema.gov/api/open/v1/NfipMultipleL...,https://www.fema.gov/openfema-data-page/NFIP-M...,"[NFIP, Insurance, Flood, Repetitive Loss, Dama...",2024-02-27T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,...,257374,None,None,None,None,c6474d2bed656468b54afcb63f3da841959535a5,2024-11-21T14:40:15.168Z,f3cfd1cd-ea0d-455c-bfcd-f99625ecd393,2024-12-17T20:40:57.000Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
3,openfema-73,FimaNfipClaims,FIMA NFIP Redacted Claims,Congress passed the National Flood Insurance A...,https://www.fema.gov/api/open/v2/FimaNfipClaims,https://www.fema.gov/openfema-data-page/fima-n...,"[NFIP, FIMA, claims, flood insurance]",2023-03-24T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,...,2713766,None,None,None,None,843979427d2c4cc20e139ce661e6b0476975431f,2024-11-21T14:40:15.168Z,e9343760-d76e-44db-b947-822642353e7f,2025-07-01T14:43:55.809Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
4,openfema-74,FimaNfipPolicies,FIMA NFIP Redacted Policies,Congress passed the National Flood Insurance A...,https://www.fema.gov/api/open/v2/FimaNfipPolicies,https://www.fema.gov/openfema-data-page/fima-n...,"[NFIP, Flood, Insurance, Policy, Water]",2025-04-01T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,...,70460966,None,None,None,None,85c6b91e237853b3333b06b4e3ebf5cdef930060,2025-04-01T20:00:37.246Z,3776bead-efe2-4590-84eb-3e000f869701,2025-07-01T15:41:59.674Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
5,openfema-77,NfipCommunityLayerComprehensive,NFIP Community Layer Comprehensive,This dataset is also known as the 3d layer and...,https://www.fema.gov/api/open/v1/NfipCommunity...,https://www.fema.gov/openfema-data-page/nfip-c...,"[nfip community, geospatial, census, boundaries]",2024-02-22T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,...,51943,None,None,None,None,51551de69709270cbb3dc05a9da88e92be099c2d,2024-12-05T22:20:23.322Z,0131d365-5a18-47a0-98cb-558149c165ee,2024-12-05T18:09:51.898Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
6,openfema-76,NfipCommunityLayerNoOverlapsSplit,NFIP Community Layer No Overlaps Split,This dataset is flattened and multicounty comm...,https://www.fema.gov/api/open/v1/NfipCommunity...,https://www.fema.gov/openfema-data-page/nfip-c...,"[nfip community, geospatial, census, boundaries]",2024-02-22T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,...,37918,None,None,None,None,8db6fcd098f2b2bf16a3dc6b10ccb93543d32010,2024-12-05T22:20:23.322Z,57d33198-ea17-4255-83fe-35742b8f601b,2024-12-05T18:09:57.312Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
7,openfema-75,NfipCommunityLayerNoOverlapsWhole,NFIP Community Layer No Overlaps Whole,This dataset is flattened and multicounty comm...,https://www.fema.gov/api/open/v1/NfipCommunity...,https://www.fema.gov/openfema-data-page/nfip-c...,"[nfip community, geospatial, census, boundaries]",2024-02-22T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,...,29898,None,None,None,None,7bdabebd0a0805adbb76fee3ca61bbd4a5f5c0b7,2024-12-05T22:20:23.322Z,e2c2268c-7a3c-4ce1-830e-ac5f735ee44c,2024-12-05T18:10:50.474Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."

In [5]:
# first 15 columns
metadata_df.iloc[:, :15]

,identifier,name,title,description,webService,dataDictionary,keyword,modified,publisher,contactPoint,mbox,accessLevel,landingPage,temporal,api
0,openfema-39,NfipCommunityStatusBook,NFIP Community Status Book,The National Flood Insurance Program (NFIP) en...,https://www.fema.gov/api/open/v1/NfipCommunity...,https://www.fema.gov/openfema-data-page/nfip-c...,"[NFIP, Status Book, Community Status Book, Flo...",2024-11-07T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,openfema@fema.gov,public,https://www.fema.gov/floodplain-management,1968-01-01/,True
1,openfema-86,NfipResidentialPenetrationRates,NFIP Residential Penetration Rates,"NFIP ""take-up rates"" or residential penetratio...",https://www.fema.gov/api/open/v1/NfipResidenti...,https://www.fema.gov/openfema-data-page/nfip-r...,"[nfip, rates, nsi, residential structures, pol...",2024-11-07T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,openfema@fema.gov,public,https://www.fema.gov/flood-insurance,None,True
2,openfema-78,NfipMultipleLossProperties,NFIP Multiple Loss Properties,This dataset provides information on structure...,https://www.fema.gov/api/open/v1/NfipMultipleL...,https://www.fema.gov/openfema-data-page/NFIP-M...,"[NFIP, Insurance, Flood, Repetitive Loss, Dama...",2024-02-27T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,openfema@fema.gov,public,https://www.fema.gov/flood-insurance,1978-01-01/,True
3,openfema-73,FimaNfipClaims,FIMA NFIP Redacted Claims,Congress passed the National Flood Insurance A...,https://www.fema.gov/api/open/v2/FimaNfipClaims,https://www.fema.gov/openfema-data-page/fima-n...,"[NFIP, FIMA, claims, flood insurance]",2023-03-24T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,openfema@fema.gov,public,https://www.fema.gov/flood-insurance,1970-08-31/,True
4,openfema-74,FimaNfipPolicies,FIMA NFIP Redacted Policies,Congress passed the National Flood Insurance A...,https://www.fema.gov/api/open/v2/FimaNfipPolicies,https://www.fema.gov/openfema-data-page/fima-n...,"[NFIP, Flood, Insurance, Policy, Water]",2025-04-01T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,openfema@fema.gov,public,https://www.fema.gov/flood-insurance,2009-01-01/,True
5,openfema-77,NfipCommunityLayerComprehensive,NFIP Community Layer Comprehensive,This dataset is also known as the 3d layer and...,https://www.fema.gov/api/open/v1/NfipCommunity...,https://www.fema.gov/openfema-data-page/nfip-c...,"[nfip community, geospatial, census, boundaries]",2024-02-22T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,openfema@fema.gov,public,https://www.fema.gov/flood-insurance,None,True
6,openfema-76,NfipCommunityLayerNoOverlapsSplit,NFIP Community Layer No Overlaps Split,This dataset is flattened and multicounty comm...,https://www.fema.gov/api/open/v1/NfipCommunity...,https://www.fema.gov/openfema-data-page/nfip-c...,"[nfip community, geospatial, census, boundaries]",2024-02-22T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,openfema@fema.gov,public,https://www.fema.gov/flood-insurance,None,True
7,openfema-75,NfipCommunityLayerNoOverlapsWhole,NFIP Community Layer No Overlaps Whole,This dataset is flattened and multicounty comm...,https://www.fema.gov/api/open/v1/NfipCommunity...,https://www.fema.gov/openfema-data-page/nfip-c...,"[nfip community, geospatial, census, boundaries]",2024-02-22T00:00:00.000Z,Federal Emergency Management Agency,OpenFEMA,openfema@fema.gov,public,https://www.fema.gov/flood-insurance,None,True

In [6]:
# next 15 columns
metadata_df.iloc[:, 15:30]

,version,bureauCode,programCode,accessLevelComment,license,spatial,theme,dataQuality,accrualPeriodicity,language,primaryITInvestmentUII,references,issued,systemOfRecords,recordCount
0,1,[024:70],[024:039],None,None,None,National Flood Insurance Program,true,R/P1D,en-US,None,[],1968-01-01T00:00:00.000Z,None,25053
1,1,[024:70],[024:039],None,None,None,National Flood Insurance Program,true,R/P3M,en-US,None,[],2024-11-08T00:00:00.000Z,None,3162
2,1,[024:70],[024:039],None,None,None,National Flood Insurance Program,true,R/P1Y,en-US,None,[https://agents.floodsmart.gov/sites/default/f...,2024-02-12T00:00:00.000Z,None,257374
3,2,[024:70],[024:039],None,None,None,National Flood Insurance Program,true,R/P1M,en-US,None,[https://nfipservices.floodsmart.gov/manuals/j...,2019-06-01T00:00:00.000Z,None,2713766
4,2,[024:70],[024:039],None,None,None,National Flood Insurance Program,true,R/P1M,en-US,None,[https://nfipservices.floodsmart.gov/manuals/j...,2019-06-01T00:00:00.000Z,None,70460966
5,1,[024:70],[024:039],None,None,None,National Flood Insurance Program,true,R/P1Y,en-US,None,[],2024-02-09T00:00:00.000Z,None,51943
6,1,[024:70],[024:039],None,None,None,National Flood Insurance Program,true,R/P1Y,en-US,None,[],2024-02-09T00:00:00.000Z,None,37918
7,1,[024:70],[024:039],None,None,None,National Flood Insurance Program,true,R/P1Y,en-US,None,[],2024-02-09T00:00:00.000Z,None,29898

In [7]:
# columns to the end
metadata_df.iloc[:, 30:]

,depDate,depApiMessage,depWebMessage,depNewURL,hash,lastRefresh,id,lastDataSetRefresh,distribution
0,None,None,None,None,7b8f6d05763d0c656c524c44438e1d8e8552abe8,2024-11-21T14:40:15.168Z,edccafe8-40f9-472a-84a9-e7cbbab850e2,2025-07-03T03:14:05.889Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
1,None,None,None,None,c84151b7bbe46b75c5143a0c9d491a9986247f06,2024-11-21T14:40:15.168Z,18f6002e-40a5-4601-9504-279b8e6bf985,2025-05-19T15:20:16.607Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
2,None,None,None,None,c6474d2bed656468b54afcb63f3da841959535a5,2024-11-21T14:40:15.168Z,f3cfd1cd-ea0d-455c-bfcd-f99625ecd393,2024-12-17T20:40:57.000Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
3,None,None,None,None,843979427d2c4cc20e139ce661e6b0476975431f,2024-11-21T14:40:15.168Z,e9343760-d76e-44db-b947-822642353e7f,2025-07-01T14:43:55.809Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
4,None,None,None,None,85c6b91e237853b3333b06b4e3ebf5cdef930060,2025-04-01T20:00:37.246Z,3776bead-efe2-4590-84eb-3e000f869701,2025-07-01T15:41:59.674Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
5,None,None,None,None,51551de69709270cbb3dc05a9da88e92be099c2d,2024-12-05T22:20:23.322Z,0131d365-5a18-47a0-98cb-558149c165ee,2024-12-05T18:09:51.898Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
6,None,None,None,None,8db6fcd098f2b2bf16a3dc6b10ccb93543d32010,2024-12-05T22:20:23.322Z,57d33198-ea17-4255-83fe-35742b8f601b,2024-12-05T18:09:57.312Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."
7,None,None,None,None,7bdabebd0a0805adbb76fee3ca61bbd4a5f5c0b7,2024-12-05T22:20:23.322Z,e2c2268c-7a3c-4ce1-830e-ac5f735ee44c,2024-12-05T18:10:50.474Z,"[{'format': 'csv', 'accessURL': 'https://www.f..."

# Download Tutorial

Code to download the NFIP Policies and Claims datasets using the OpenFEMA API. In this tutorial, we only export data in New York City. Note: We can also download the files in bulk as Parquet files.

In [8]:
BASE_URL = "https://www.fema.gov/api/open/v2/FimaNfip{}"
PAGE_SIZE = 10_000
ALLOWED_DATASETS = {"Claims", "Policies"}

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

def build_url(dataset, fips, skip):
    return (
        f"{BASE_URL.format(dataset)}"
        "?$format=parquet"
        f"&$filter=countyCode eq '{fips}'"
        f"&$top={PAGE_SIZE}"
        f"&$skip={skip}"
    )

def fetch_nfip_data(dataset, fips, outpath=".", sleep_secs=2.0):
    dataset_cap = dataset.capitalize()
    if dataset_cap not in ALLOWED_DATASETS:
        raise ValueError(f"Invalid dataset '{dataset}'. Must be one of {ALLOWED_DATASETS}")

    os.makedirs(outpath, exist_ok=True)
    output_file = os.path.join(outpath, f"{dataset.lower()}-{fips}.parquet")

    with tempfile.TemporaryDirectory() as tmpdir:
        skip = 0
        total_records = 0

        logging.info(f"Starting download for FIPS {fips}, dataset '{dataset_cap}'")

        while True:
            url = build_url(dataset_cap, fips, skip)
            logging.info(f"Requesting page: skip={skip}")

            page_path = os.path.join(tmpdir, f"page_{skip}.parquet")

            try:
                response = requests.get(url, timeout=60)
                response.raise_for_status()
                with open(page_path, "wb") as f:
                    for chunk in response.iter_content(chunk_size=8192):
                        f.write(chunk)
            except Exception as e:
                logging.error(f"Request failed at skip={skip}: {e}")
                raise

            try:
                con = duckdb.connect()
                result = con.execute(f"SELECT COUNT(*) FROM read_parquet('{page_path}')").fetchone()
                page_count = result[0]
                con.close()
            except Exception as e:
                logging.error(f"Parquet read failed at skip={skip}: {e}")
                os.remove(page_path)
                raise

            if page_count == 0:
                logging.info(f"No more data returned at skip={skip}. Ending.")
                os.remove(page_path)
                break

            total_records += page_count
            logging.info(f"Page loaded: {page_count} records")

            if page_count < PAGE_SIZE:
                logging.info("Final page detected.")
                break

            skip += PAGE_SIZE
            time.sleep(sleep_secs)

        if total_records > 0:
            try:
                con = duckdb.connect()
                input_glob = os.path.join(tmpdir, "*.parquet")
                con.execute(f"""
                    COPY (SELECT * FROM read_parquet('{input_glob}'))
                    TO '{output_file}' (FORMAT PARQUET)
                """)
                logging.info(f"Wrote {total_records} records to {output_file}")
                con.close()
            except Exception as e:
                logging.error(f"Failed to write output Parquet: {e}")
                raise
        else:
            logging.warning("No data fetched. Nothing saved.")

# OpenFEMA Dataset: FIMA NFIP Redacted Claims - v2
https://www.fema.gov/openfema-data-page/fima-nfip-redacted-claims-v2

In [9]:
%%time

fips_list = [
    "36005",
    "36047",
    "36061",
    "36081",
    "36085"
]

dataset = "Claims"
outpath = "data/"

for fips in fips_list:
    fetch_nfip_data(dataset, fips, outpath)

2025-07-02 23:17:59,313 - INFO - Starting download for FIPS 36005, dataset 'Claims'
2025-07-02 23:17:59,314 - INFO - Requesting page: skip=0
2025-07-02 23:17:59,599 - INFO - Page loaded: 1942 records
2025-07-02 23:17:59,600 - INFO - Final page detected.
2025-07-02 23:17:59,630 - INFO - Wrote 1942 records to data/claims-36005.parquet
2025-07-02 23:17:59,633 - INFO - Starting download for FIPS 36047, dataset 'Claims'
2025-07-02 23:17:59,634 - INFO - Requesting page: skip=0
2025-07-02 23:18:00,010 - INFO - Page loaded: 6265 records
2025-07-02 23:18:00,011 - INFO - Final page detected.
2025-07-02 23:18:00,071 - INFO - Wrote 6265 records to data/claims-36047.parquet
2025-07-02 23:18:00,075 - INFO - Starting download for FIPS 36061, dataset 'Claims'
2025-07-02 23:18:00,075 - INFO - Requesting page: skip=0
2025-07-02 23:18:00,327 - INFO - Page loaded: 1484 records
2025-07-02 23:18:00,328 - INFO - Final page detected.
2025-07-02 23:18:00,359 - INFO - Wrote 1484 records to data/claims-36061.parquet
2025-07-02 23:18:00,362 - INFO - Starting download for FIPS 36081, dataset 'Claims'
2025-07-02 23:18:00,363 - INFO - Requesting page: skip=0
2025-07-02 23:18:00,808 - INFO - Page loaded: 10000 records
2025-07-02 23:18:02,814 - INFO - Requesting page: skip=10000
2025-07-02 23:18:03,303 - INFO - Page loaded: 4876 records
2025-07-02 23:18:03,304 - INFO - Final page detected.
2025-07-02 23:18:03,415 - INFO - Wrote 14876 records to data/claims-36081.parquet
2025-07-02 23:18:03,419 - INFO - Starting download for FIPS 36085, dataset 'Claims'
2025-07-02 23:18:03,419 - INFO - Requesting page: skip=0
2025-07-02 23:18:03,879 - INFO - Page loaded: 10000 records
2025-07-02 23:18:05,885 - INFO - Requesting page: skip=10000
2025-07-02 23:18:06,206 - INFO - Page loaded: 9414 records
2025-07-02 23:18:06,207 - INFO - Final page detected.
2025-07-02 23:18:06,338 - INFO - Wrote 19414 records to data/claims-36085.parquet

CPU times: user 803 ms, sys: 165 ms, total: 968 ms
Wall time: 7.03 s

In [10]:
# count rows
duckdb.sql("""
    SELECT count(*) AS count_rows
    FROM read_parquet('data/claims-*.parquet')
""")

┌────────────┐
│ count_rows │
│   int64    │
├────────────┤
│      43981 │
└────────────┘

In [11]:
# preview first five rows
duckdb.sql("""
    SELECT *
    FROM read_parquet('data/claims-*.parquet')
    LIMIT 5
""").show()

┌──────────────────────┬──────────────────────┬─────────────────────┬───┬──────────────────────┬──────────┬───────────┐
│          id          │ agricultureStructu…  │      asOfDate       │ … │ censusBlockGroupFips │ latitude │ longitude │
│       varchar        │       boolean        │      timestamp      │   │       varchar        │  double  │  double   │
├──────────────────────┼──────────────────────┼─────────────────────┼───┼──────────────────────┼──────────┼───────────┤
│ 166eb26d-1103-4b12…  │ false                │ 2025-07-01 00:00:00 │ … │ 360050138001         │     40.8 │     -73.8 │
│ 8df05ef8-3d60-4ad6…  │ false                │ 2025-07-01 00:00:00 │ … │ 360050016004         │     40.8 │     -73.9 │
│ 620455d6-0292-4fe3…  │ false                │ 2025-07-01 00:00:00 │ … │ 360050118001         │     40.8 │     -73.8 │
│ 767fd936-dbb7-477d…  │ false                │ 2025-07-01 00:00:00 │ … │ 360050356002         │     40.9 │     -73.8 │
│ 7ba25015-1caf-44f4…  │ false                │ 2025-07-01 00:00:00 │ … │ 360050132003         │     40.8 │     -73.8 │
├──────────────────────┴──────────────────────┴─────────────────────┴───┴──────────────────────┴──────────┴───────────┤
│ 5 rows                                                                                         73 columns (6 shown) │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [12]:
# preview columns
duckdb.sql("""
    SELECT
        column_name,
        column_type,
        null_percentage
    FROM (SUMMARIZE (FROM read_parquet('data/claims-*.parquet')))
    ORDER BY null_percentage DESC
""").show(max_rows=80)

┌────────────────────────────────────────────┬─────────────┬─────────────────┐
│                column_name                 │ column_type │ null_percentage │
│                  varchar                   │   varchar   │  decimal(9,2)   │
├────────────────────────────────────────────┼─────────────┼─────────────────┤
│ crsClassificationCode                      │ SMALLINT    │          100.00 │
│ floodCharacteristicsIndicator              │ SMALLINT    │           99.70 │
│ eventDesignationNumber                     │ VARCHAR     │           97.31 │
│ lowestAdjacentGrade                        │ DOUBLE      │           87.20 │
│ lowestFloorElevation                       │ DOUBLE      │           86.93 │
│ baseFloodElevation                         │ DOUBLE      │           86.62 │
│ elevationDifference                        │ DOUBLE      │           86.50 │
│ nonPaymentReasonBuilding                   │ VARCHAR     │           80.11 │
│ nonPaymentReasonContents                   │ VARCHAR     │           74.24 │
│ nfipCommunityNumberCurrent                 │ VARCHAR     │           73.34 │
│ floodZoneCurrent                           │ VARCHAR     │           73.34 │
│ nfipCommunityName                          │ VARCHAR     │           72.56 │
│ elevationCertificateIndicator              │ VARCHAR     │           70.74 │
│ buildingDescriptionCode                    │ SMALLINT    │           60.24 │
│ contentsDamageAmount                       │ BIGINT      │           55.09 │
│ contentsPropertyValue                      │ BIGINT      │           55.09 │
│ contentsReplacementCost                    │ BIGINT      │           55.09 │
│ obstructionType                            │ SMALLINT    │           53.50 │
│ contentsDeductibleCode                     │ VARCHAR     │           44.08 │
│ basementEnclosureCrawlspaceType            │ SMALLINT    │           42.93 │
│ iccCoverage                                │ INTEGER     │           41.73 │
│ ficoNumber                                 │ SMALLINT    │           36.62 │
│ locationOfContents                         │ SMALLINT    │           36.08 │
│ ratedFloodZone                             │ VARCHAR     │           33.85 │
│ floodEvent                                 │ VARCHAR     │           32.89 │
│ buildingDeductibleCode                     │ VARCHAR     │           31.00 │
│ buildingDamageAmount                       │ BIGINT      │           21.15 │
│ buildingPropertyValue                      │ BIGINT      │           21.15 │
│ buildingReplacementCost                    │ BIGINT      │           21.15 │
│ amountPaidOnBuildingClaim                  │ DOUBLE      │           16.04 │
│ amountPaidOnContentsClaim                  │ DOUBLE      │           16.04 │
│ amountPaidOnIncreasedCostOfComplianceClaim │ DOUBLE      │           16.04 │
│ disasterAssistanceCoverageRequired         │ SMALLINT    │           12.88 │
│ replacementCostBasis                       │ VARCHAR     │            8.21 │
│ floodWaterDuration                         │ SMALLINT    │            5.89 │
│ waterDepth                                 │ SMALLINT    │            5.01 │
│ condominiumCoverageTypeCode                │ VARCHAR     │            4.92 │
│ rateMethod                                 │ VARCHAR     │            4.89 │
│ censusTract                                │ VARCHAR     │            0.87 │
│ censusBlockGroupFips                       │ VARCHAR     │            0.87 │
│ causeOfDamage                              │ VARCHAR     │            0.55 │
│ numberOfFloorsInTheInsuredBuilding         │ SMALLINT    │            0.18 │
│ occupancyType                              │ SMALLINT    │            0.06 │
│ numberOfUnits                              │ INTEGER     │            0.04 │
│ originalConstructionDate                   │ DATE        │            0.01 │
│ id                                         │ VARCHAR     │            0.00 │
│ agricultureStructureIndicator              │ BOOLEAN     │            0.00 │
│ asOfDate                                   │ TIMESTAMP   │            0.00 │
│ policyCount                                │ SMALLINT    │            0.00 │
│ dateOfLoss                                 │ DATE        │            0.00 │
│ elevatedBuildingIndicator                  │ BOOLEAN     │            0.00 │
│ houseWorship                               │ BOOLEAN     │            0.00 │
│ nonProfitIndicator                         │ BOOLEAN     │            0.00 │
│ originalNBDate                             │ DATE        │            0.00 │
│ postFIRMConstructionIndicator              │ BOOLEAN     │            0.00 │
│ smallBusinessIndicatorBuilding             │ BOOLEAN     │            0.00 │
│ totalBuildingInsuranceCoverage             │ BIGINT      │            0.00 │
│ totalContentsInsuranceCoverage             │ BIGINT      │            0.00 │
│ yearOfLoss                                 │ SMALLINT    │            0.00 │
│ primaryResidenceIndicator                  │ BOOLEAN     │            0.00 │
│ netBuildingPaymentAmount                   │ DOUBLE      │            0.00 │
│ netContentsPaymentAmount                   │ DOUBLE      │            0.00 │
│ floodproofedIndicator                      │ BOOLEAN     │            0.00 │
│ netIccPaymentAmount                        │ DOUBLE      │            0.00 │
│ nfipRatedCommunityNumber                   │ VARCHAR     │            0.00 │
│ stateOwnedIndicator                        │ BOOLEAN     │            0.00 │
│ rentalPropertyIndicator                    │ BOOLEAN     │            0.00 │
│ state                                      │ VARCHAR     │            0.00 │
│ reportedCity                               │ VARCHAR     │            0.00 │
│ reportedZipCode                            │ VARCHAR     │            0.00 │
│ countyCode                                 │ VARCHAR     │            0.00 │
│ latitude                                   │ DOUBLE      │            0.00 │
│ longitude                                  │ DOUBLE      │            0.00 │
├────────────────────────────────────────────┴─────────────┴─────────────────┤
│ 73 rows                                                          3 columns │
└────────────────────────────────────────────────────────────────────────────┘

# OpenFEMA Dataset: FIMA NFIP Redacted Policies - v2
https://www.fema.gov/openfema-data-page/fima-nfip-redacted-policies-v2

In [13]:
%%time

fips_list = [
    "36005",
    "36047",
    "36061",
    "36081",
    "36085"
]

dataset = "Policies"
outpath = "data/"

for fips in fips_list:
    fetch_nfip_data(dataset, fips, outpath)

2025-07-02 23:18:06,636 - INFO - Starting download for FIPS 36005, dataset 'Policies'
2025-07-02 23:18:06,637 - INFO - Requesting page: skip=0
2025-07-02 23:18:11,345 - INFO - Page loaded: 10000 records
2025-07-02 23:18:13,351 - INFO - Requesting page: skip=10000
2025-07-02 23:18:18,626 - INFO - Page loaded: 10000 records
2025-07-02 23:18:20,632 - INFO - Requesting page: skip=20000
2025-07-02 23:18:25,926 - INFO - Page loaded: 10000 records
2025-07-02 23:18:27,932 - INFO - Requesting page: skip=30000
2025-07-02 23:18:31,623 - INFO - Page loaded: 5838 records
2025-07-02 23:18:31,624 - INFO - Final page detected.
2025-07-02 23:18:31,855 - INFO - Wrote 35838 records to data/policies-36005.parquet
2025-07-02 23:18:31,859 - INFO - Starting download for FIPS 36047, dataset 'Policies'
2025-07-02 23:18:31,860 - INFO - Requesting page: skip=0
2025-07-02 23:18:38,909 - INFO - Page loaded: 10000 records
2025-07-02 23:18:40,915 - INFO - Requesting page: skip=10000
2025-07-02 23:18:48,840 - INFO - Page loaded: 10000 records
2025-07-02 23:18:50,842 - INFO - Requesting page: skip=20000
2025-07-02 23:18:58,151 - INFO - Page loaded: 10000 records
2025-07-02 23:19:00,157 - INFO - Requesting page: skip=30000
2025-07-02 23:19:07,705 - INFO - Page loaded: 10000 records
2025-07-02 23:19:09,709 - INFO - Requesting page: skip=40000
2025-07-02 23:19:17,166 - INFO - Page loaded: 10000 records
2025-07-02 23:19:19,167 - INFO - Requesting page: skip=50000
2025-07-02 23:19:26,788 - INFO - Page loaded: 10000 records
2025-07-02 23:19:28,794 - INFO - Requesting page: skip=60000
2025-07-02 23:19:36,152 - INFO - Page loaded: 10000 records
2025-07-02 23:19:38,155 - INFO - Requesting page: skip=70000
2025-07-02 23:19:45,467 - INFO - Page loaded: 10000 records
2025-07-02 23:19:47,473 - INFO - Requesting page: skip=80000
2025-07-02 23:19:54,579 - INFO - Page loaded: 10000 records
2025-07-02 23:19:56,581 - INFO - Requesting page: skip=90000
2025-07-02 23:20:05,397 - INFO - Page loaded: 10000 records
2025-07-02 23:20:07,400 - INFO - Requesting page: skip=100000
2025-07-02 23:20:14,731 - INFO - Page loaded: 10000 records
2025-07-02 23:20:16,734 - INFO - Requesting page: skip=110000
2025-07-02 23:20:24,166 - INFO - Page loaded: 10000 records
2025-07-02 23:20:26,170 - INFO - Requesting page: skip=120000
2025-07-02 23:20:33,593 - INFO - Page loaded: 10000 records
2025-07-02 23:20:35,599 - INFO - Requesting page: skip=130000
2025-07-02 23:20:43,628 - INFO - Page loaded: 10000 records
2025-07-02 23:20:45,634 - INFO - Requesting page: skip=140000
2025-07-02 23:20:53,048 - INFO - Page loaded: 10000 records
2025-07-02 23:20:55,051 - INFO - Requesting page: skip=150000
2025-07-02 23:20:58,456 - INFO - Page loaded: 3930 records
2025-07-02 23:20:58,457 - INFO - Final page detected.
2025-07-02 23:20:59,272 - INFO - Wrote 153930 records to data/policies-36047.parquet
2025-07-02 23:20:59,280 - INFO - Starting download for FIPS 36061, dataset 'Policies'
2025-07-02 23:20:59,281 - INFO - Requesting page: skip=0
2025-07-02 23:21:04,689 - INFO - Page loaded: 10000 records
2025-07-02 23:21:06,695 - INFO - Requesting page: skip=10000
2025-07-02 23:21:13,756 - INFO - Page loaded: 10000 records
2025-07-02 23:21:15,762 - INFO - Requesting page: skip=20000
2025-07-02 23:21:20,396 - INFO - Page loaded: 10000 records
2025-07-02 23:21:22,402 - INFO - Requesting page: skip=30000
2025-07-02 23:21:27,001 - INFO - Page loaded: 8259 records
2025-07-02 23:21:27,002 - INFO - Final page detected.
2025-07-02 23:21:27,244 - INFO - Wrote 38259 records to data/policies-36061.parquet
2025-07-02 23:21:27,248 - INFO - Starting download for FIPS 36081, dataset 'Policies'
2025-07-02 23:21:27,249 - INFO - Requesting page: skip=0
2025-07-02 23:21:38,411 - INFO - Page loaded: 10000 records
2025-07-02 23:21:40,416 - INFO - Requesting page: skip=10000
2025-07-02 23:21:47,101 - INFO - Page loaded: 10000 records
2025-07-02 23:21:49,107 - INFO - Requesting page: skip=20000
2025-07-02 23:21:56,228 - INFO - Page loaded: 10000 records
2025-07-02 23:21:58,234 - INFO - Requesting page: skip=30000
2025-07-02 23:22:06,061 - INFO - Page loaded: 10000 records
2025-07-02 23:22:08,067 - INFO - Requesting page: skip=40000
2025-07-02 23:22:14,612 - INFO - Page loaded: 10000 records
2025-07-02 23:22:16,618 - INFO - Requesting page: skip=50000
2025-07-02 23:22:23,877 - INFO - Page loaded: 10000 records
2025-07-02 23:22:25,883 - INFO - Requesting page: skip=60000
2025-07-02 23:22:34,393 - INFO - Page loaded: 10000 records
2025-07-02 23:22:36,395 - INFO - Requesting page: skip=70000
2025-07-02 23:22:42,370 - INFO - Page loaded: 10000 records
2025-07-02 23:22:44,376 - INFO - Requesting page: skip=80000
2025-07-02 23:22:50,911 - INFO - Page loaded: 10000 records
2025-07-02 23:22:52,917 - INFO - Requesting page: skip=90000
2025-07-02 23:22:59,564 - INFO - Page loaded: 10000 records
2025-07-02 23:23:01,570 - INFO - Requesting page: skip=100000
2025-07-02 23:23:08,470 - INFO - Page loaded: 10000 records
2025-07-02 23:23:10,476 - INFO - Requesting page: skip=110000
2025-07-02 23:23:17,075 - INFO - Page loaded: 10000 records
2025-07-02 23:23:19,080 - INFO - Requesting page: skip=120000
2025-07-02 23:23:25,625 - INFO - Page loaded: 10000 records
2025-07-02 23:23:27,630 - INFO - Requesting page: skip=130000
2025-07-02 23:23:34,595 - INFO - Page loaded: 10000 records
2025-07-02 23:23:36,601 - INFO - Requesting page: skip=140000
2025-07-02 23:23:44,084 - INFO - Page loaded: 10000 records
2025-07-02 23:23:46,090 - INFO - Requesting page: skip=150000
2025-07-02 23:23:52,658 - INFO - Page loaded: 10000 records
2025-07-02 23:23:54,663 - INFO - Requesting page: skip=160000
2025-07-02 23:24:02,516 - INFO - Page loaded: 10000 records
2025-07-02 23:24:04,518 - INFO - Requesting page: skip=170000
2025-07-02 23:24:12,319 - INFO - Page loaded: 10000 records
2025-07-02 23:24:14,325 - INFO - Requesting page: skip=180000
2025-07-02 23:24:21,378 - INFO - Page loaded: 10000 records
2025-07-02 23:24:23,384 - INFO - Requesting page: skip=190000
2025-07-02 23:24:30,444 - INFO - Page loaded: 10000 records
2025-07-02 23:24:32,450 - INFO - Requesting page: skip=200000
2025-07-02 23:24:39,353 - INFO - Page loaded: 10000 records
2025-07-02 23:24:41,354 - INFO - Requesting page: skip=210000
2025-07-02 23:24:48,266 - INFO - Page loaded: 10000 records
2025-07-02 23:24:50,272 - INFO - Requesting page: skip=220000
2025-07-02 23:24:54,302 - INFO - Page loaded: 4557 records
2025-07-02 23:24:54,303 - INFO - Final page detected.
2025-07-02 23:24:55,621 - INFO - Wrote 224557 records to data/policies-36081.parquet
2025-07-02 23:24:55,629 - INFO - Starting download for FIPS 36085, dataset 'Policies'
2025-07-02 23:24:55,629 - INFO - Requesting page: skip=0
2025-07-02 23:25:02,704 - INFO - Page loaded: 10000 records
2025-07-02 23:25:04,705 - INFO - Requesting page: skip=10000
2025-07-02 23:25:11,614 - INFO - Page loaded: 10000 records
2025-07-02 23:25:13,615 - INFO - Requesting page: skip=20000
2025-07-02 23:25:19,935 - INFO - Page loaded: 10000 records
2025-07-02 23:25:21,941 - INFO - Requesting page: skip=30000
2025-07-02 23:25:29,192 - INFO - Page loaded: 10000 records
2025-07-02 23:25:31,198 - INFO - Requesting page: skip=40000
2025-07-02 23:25:38,324 - INFO - Page loaded: 10000 records
2025-07-02 23:25:40,328 - INFO - Requesting page: skip=50000
2025-07-02 23:25:46,862 - INFO - Page loaded: 10000 records
2025-07-02 23:25:48,864 - INFO - Requesting page: skip=60000
2025-07-02 23:25:55,614 - INFO - Page loaded: 10000 records
2025-07-02 23:25:57,615 - INFO - Requesting page: skip=70000
2025-07-02 23:26:04,055 - INFO - Page loaded: 10000 records
2025-07-02 23:26:06,061 - INFO - Requesting page: skip=80000
2025-07-02 23:26:12,950 - INFO - Page loaded: 10000 records
2025-07-02 23:26:14,956 - INFO - Requesting page: skip=90000
2025-07-02 23:26:21,991 - INFO - Page loaded: 10000 records
2025-07-02 23:26:23,995 - INFO - Requesting page: skip=100000
2025-07-02 23:26:28,764 - INFO - Page loaded: 5746 records
2025-07-02 23:26:28,765 - INFO - Final page detected.
2025-07-02 23:26:29,418 - INFO - Wrote 105746 records to data/policies-36085.parquet

CPU times: user 8.16 s, sys: 1.78 s, total: 9.94 s
Wall time: 8min 22s

In [14]:
# count rows
duckdb.sql("""
    SELECT count(*) AS count_rows
    FROM read_parquet('data/policies-*.parquet')
""")

┌────────────┐
│ count_rows │
│   int64    │
├────────────┤
│     558330 │
└────────────┘

In [15]:
# preview first five rows
duckdb.sql("""
    SELECT *
    FROM read_parquet('data/policies-*.parquet')
    LIMIT 5
""").df()

,agricultureStructureIndicator,baseFloodElevation,basementEnclosureCrawlspaceType,cancellationDateOfFloodPolicy,condominiumCoverageTypeCode,construction,crsClassCode,buildingDeductibleCode,contentsDeductibleCode,elevatedBuildingIndicator,...,femaRegion,propertyState,reportedCity,reportedZipCode,countyCode,censusTract,censusBlockGroupFips,latitude,longitude,id
0,False,13.0,0.0,NaT,N,False,NaN,0,0,False,...,2,NY,Currently Unavailable,10473,36005,36005000400,360050004004,40.8,-73.8,14ac971a-c132-4be4-a7d2-271e070d8409
1,False,NaN,NaN,NaT,N,False,NaN,0,0,False,...,2,NY,Currently Unavailable,10475,36005,36005030200,360050302003,40.9,-73.8,1204f3fa-e89c-43a4-97b6-748821f25a6e
2,False,NaN,2.0,NaT,N,False,NaN,None,0,False,...,2,NY,Currently Unavailable,10462,36005,36005009200,360050092002,40.8,-73.8,c1a1e1a0-5405-41bf-820e-76027c83697a
3,False,NaN,1.0,NaT,N,False,NaN,5,5,False,...,2,NY,Currently Unavailable,10474,36005,36005009300,360050093001,40.8,-73.9,0e0b7eca-7cac-4d86-a500-1ac581f66961
4,False,NaN,1.0,NaT,N,False,NaN,None,0,False,...,2,NY,Currently Unavailable,10465,36005,36005016000,360050160002,40.8,-73.8,e58aaba4-9b1b-4a88-8849-3ed3788c2dd7

In [16]:
# preview columns
duckdb.sql("""
    SELECT
        column_name,
        column_type,
        null_percentage
    FROM (SUMMARIZE (FROM read_parquet('data/policies-*.parquet')))
    ORDER BY null_percentage DESC
""").show(max_rows=100)

┌────────────────────────────────────────┬─────────────┬─────────────────┐
│              column_name               │ column_type │ null_percentage │
│                varchar                 │   varchar   │  decimal(9,2)   │
├────────────────────────────────────────┼─────────────┼─────────────────┤
│ crsClassCode                           │ SMALLINT    │           99.98 │
│ cancellationDateOfFloodPolicy          │ DATE        │           97.35 │
│ cancellationVoidanceReasonCode         │ VARCHAR     │           97.35 │
│ obstructionType                        │ SMALLINT    │           87.76 │
│ lowestAdjacentGrade                    │ DOUBLE      │           78.09 │
│ baseFloodElevation                     │ DOUBLE      │           78.06 │
│ lowestFloorElevation                   │ DOUBLE      │           78.02 │
│ elevationDifference                    │ INTEGER     │           78.00 │
│ propertyPurchaseDate                   │ DATE        │           67.21 │
│ elevationCertificateIndicator          │ VARCHAR     │           64.90 │
│ enclosureTypeCode                      │ VARCHAR     │           63.02 │
│ insuranceToValueCode                   │ SMALLINT    │           54.41 │
│ subsidizedRateType                     │ VARCHAR     │           49.47 │
│ premiumPaymentIndicator                │ SMALLINT    │           48.06 │
│ locationOfContents                     │ SMALLINT    │           34.47 │
│ waitingPeriodType                      │ VARCHAR     │           29.78 │
│ disasterAssistanceCoverageRequiredCode │ SMALLINT    │           27.03 │
│ floodZoneCurrent                       │ VARCHAR     │           26.16 │
│ endorsementEffectiveDate               │ DATE        │           24.09 │
│ basicContentsRate                      │ DOUBLE      │           22.48 │
│ AdditionalContentsRate                 │ DOUBLE      │           22.48 │
│ basicBuildingRate                      │ DOUBLE      │           22.47 │
│ additionalBuildingRate                 │ DOUBLE      │           22.47 │
│ basementEnclosureCrawlspaceType        │ SMALLINT    │           22.46 │
│ buildingDescriptionCode                │ SMALLINT    │           21.33 │
│ nfipCommunityName                      │ VARCHAR     │           20.83 │
│ communityProbationSurcharge            │ SMALLINT    │           20.24 │
│ contentsDeductibleCode                 │ VARCHAR     │           18.73 │
│ grandfatheringTypeCode                 │ SMALLINT    │            6.93 │
│ mapPanelNumber                         │ VARCHAR     │            5.99 │
│ mapPanelSuffix                         │ VARCHAR     │            5.73 │
│ buildingReplacementCost                │ BIGINT      │            5.33 │
│ buildingDeductibleCode                 │ VARCHAR     │            3.01 │
│ iccPremium                             │ SMALLINT    │            1.43 │
│ numberOfFloorsInInsuredBuilding        │ SMALLINT    │            0.42 │
│ ratedFloodZone                         │ VARCHAR     │            0.39 │
│ rolloverTransferCode                   │ VARCHAR     │            0.29 │
│ censusTract                            │ VARCHAR     │            0.06 │
│ censusBlockGroupFips                   │ VARCHAR     │            0.06 │
│ condominiumCoverageTypeCode            │ VARCHAR     │            0.03 │
│ originalConstructionDate               │ DATE        │            0.03 │
│ originalNBDate                         │ DATE        │            0.02 │
│ agricultureStructureIndicator          │ BOOLEAN     │            0.00 │
│ construction                           │ BOOLEAN     │            0.00 │
│ elevatedBuildingIndicator              │ BOOLEAN     │            0.00 │
│ federalPolicyFee                       │ SMALLINT    │            0.00 │
│ hfiaaSurcharge                         │ SMALLINT    │            0.00 │
│ houseOfWorshipIndicator                │ BOOLEAN     │            0.00 │
│ nonProfitIndicator                     │ BOOLEAN     │            0.00 │
│ occupancyType                          │ SMALLINT    │            0.00 │
│ policyCost                             │ INTEGER     │            0.00 │
│ policyCount                            │ SMALLINT    │            0.00 │
│ policyEffectiveDate                    │ DATE        │            0.00 │
│ policyTerminationDate                  │ DATE        │            0.00 │
│ policyTermIndicator                    │ SMALLINT    │            0.00 │
│ postFIRMConstructionIndicator          │ BOOLEAN     │            0.00 │
│ primaryResidenceIndicator              │ BOOLEAN     │            0.00 │
│ rateMethod                             │ VARCHAR     │            0.00 │
│ regularEmergencyProgramIndicator       │ VARCHAR     │            0.00 │
│ smallBusinessIndicatorBuilding         │ BOOLEAN     │            0.00 │
│ totalBuildingInsuranceCoverage         │ INTEGER     │            0.00 │
│ totalContentsInsuranceCoverage         │ INTEGER     │            0.00 │
│ totalInsurancePremiumOfThePolicy       │ INTEGER     │            0.00 │
│ reserveFundAssessment                  │ INTEGER     │            0.00 │
│ postFirmVzoneIndicator                 │ BOOLEAN     │            0.00 │
│ floodproofedIndicator                  │ BOOLEAN     │            0.00 │
│ rentalPropertyIndicator                │ BOOLEAN     │            0.00 │
│ tenantIndicator                        │ BOOLEAN     │            0.00 │
│ stateOwnedIndicator                    │ BOOLEAN     │            0.00 │
│ mandatoryPurchaseFlag                  │ BOOLEAN     │            0.00 │
│ nfipRatedCommunityNumber               │ VARCHAR     │            0.00 │
│ nfipCommunityNumberCurrent             │ VARCHAR     │            0.00 │
│ programTypeIndicator                   │ BOOLEAN     │            0.00 │
│ femaRegion                             │ SMALLINT    │            0.00 │
│ propertyState                          │ VARCHAR     │            0.00 │
│ reportedCity                           │ VARCHAR     │            0.00 │
│ reportedZipCode                        │ VARCHAR     │            0.00 │
│ countyCode                             │ VARCHAR     │            0.00 │
│ latitude                               │ DOUBLE      │            0.00 │
│ longitude                              │ DOUBLE      │            0.00 │
│ id                                     │ VARCHAR     │            0.00 │
├────────────────────────────────────────┴─────────────┴─────────────────┤
│ 81 rows                                                      3 columns │
└────────────────────────────────────────────────────────────────────────┘

# OpenFEMA Dataset: NFIP Multiple Loss Properties - v1
https://www.fema.gov/openfema-data-page/nfip-multiple-loss-properties-v1

In [17]:
%%time

# URL of the Parquet file to download
url = "https://www.fema.gov/api/open/v1/NfipMultipleLossProperties.parquet"

# path of saved file
file_path = "data/NfipMultipleLossProperties.parquet"

# send an HTTP GET request to the URL
response = requests.get(url)

# check if the request was successful (status code 200)
if response.status_code == 200:
    
    # write the content of the response to a file
    with open(file_path, 'wb') as file:
        file.write(response.content)
    print("File downloaded successfully.")
    
else:
    print("Failed to download file.")

File downloaded successfully.
CPU times: user 294 ms, sys: 47.3 ms, total: 342 ms
Wall time: 38.7 s

In [18]:
# count rows
duckdb.sql("""
    SELECT count(*) AS count_rows
    FROM read_parquet('data/NfipMultipleLossProperties.parquet')
""")

┌────────────┐
│ count_rows │
│   int64    │
├────────────┤
│     257374 │
└────────────┘

In [19]:
# preview first five rows
duckdb.sql("""
    SELECT *
    FROM read_parquet('data/NfipMultipleLossProperties.parquet')
    LIMIT 5
""").df()

,fipsCountyCode,state,stateAbbreviation,county,zipCode,reportedCity,communityIdNumber,communityName,censusBlockGroup,nfipRl,...,occupancyType,originalConstructionDate,originalNBDate,postFIRMConstructionIndicator,primaryResidenceIndicator,mitigatedIndicator,insuredIndicator,totalLosses,mostRecentDateofLoss,id
0,01001,Alabama,AL,AUTAUGA COUNTY,36066,PRATTVILLE,010002,"PRATTVILLE, CITY OF",010010204001,True,...,11,1978-09-15,2023-06-07,True,False,False,True,2,2009-05-07,83afd8dc-c235-4f88-9870-095ea987764a
1,01001,Alabama,AL,AUTAUGA COUNTY,36067,PRATTVILLE,010002,"PRATTVILLE, CITY OF",010010207003,True,...,14,1989-01-01,2023-09-02,True,True,False,True,3,2024-01-09,c93a7608-09d4-482e-9ca7-799bf4e8f977
2,01001,Alabama,AL,AUTAUGA COUNTY,36067,PRATTVILLE,010002,"PRATTVILLE, CITY OF",010010202002,True,...,4,1935-01-01,2009-02-02,False,False,True,False,3,2009-05-07,0e19f3a6-2b31-4d94-b5fe-eec5985be6da
3,01001,Alabama,AL,AUTAUGA COUNTY,36066,PRATTVILLE,010002,"PRATTVILLE, CITY OF",010010204001,False,...,1,1976-07-01,1986-01-25,False,True,True,False,5,2000-09-01,1b298520-0bc9-484c-820b-3b86ba949caf
4,01001,Alabama,AL,AUTAUGA COUNTY,36067,PRATTVILLE,010002,"PRATTVILLE, CITY OF",010010207003,True,...,4,1978-01-01,1997-07-13,False,False,False,False,4,2000-09-01,1bba2518-673b-422a-a8d2-d2954d0b6c27

In [20]:
# preview columns
duckdb.sql("""
    SELECT
        column_name,
        column_type,
        null_percentage
    FROM (SUMMARIZE (FROM read_parquet('data/NfipMultipleLossProperties.parquet')))
    ORDER BY null_percentage DESC
""").show(max_rows=100)

┌───────────────────────────────┬─────────────┬─────────────────┐
│          column_name          │ column_type │ null_percentage │
│            varchar            │   varchar   │  decimal(9,2)   │
├───────────────────────────────┼─────────────┼─────────────────┤
│ originalConstructionDate      │ DATE        │            6.01 │
│ censusBlockGroup              │ VARCHAR     │            4.19 │
│ latitude                      │ DOUBLE      │            4.19 │
│ longitude                     │ DOUBLE      │            4.19 │
│ zipCode                       │ VARCHAR     │            1.36 │
│ county                        │ VARCHAR     │            1.21 │
│ reportedCity                  │ VARCHAR     │            0.13 │
│ totalLosses                   │ SMALLINT    │            0.10 │
│ postFIRMConstructionIndicator │ BOOLEAN     │            0.09 │
│ mostRecentDateofLoss          │ DATE        │            0.09 │
│ fipsCountyCode                │ VARCHAR     │            0.03 │
│ occupancyType                 │ SMALLINT    │            0.01 │
│ originalNBDate                │ DATE        │            0.01 │
│ state                         │ VARCHAR     │            0.00 │
│ stateAbbreviation             │ VARCHAR     │            0.00 │
│ communityIdNumber             │ VARCHAR     │            0.00 │
│ communityName                 │ VARCHAR     │            0.00 │
│ nfipRl                        │ BOOLEAN     │            0.00 │
│ nfipSrl                       │ BOOLEAN     │            0.00 │
│ fmaRl                         │ BOOLEAN     │            0.00 │
│ fmaSrl                        │ BOOLEAN     │            0.00 │
│ asOfDate                      │ DATE        │            0.00 │
│ floodZone                     │ VARCHAR     │            0.00 │
│ primaryResidenceIndicator     │ BOOLEAN     │            0.00 │
│ mitigatedIndicator            │ BOOLEAN     │            0.00 │
│ insuredIndicator              │ BOOLEAN     │            0.00 │
│ id                            │ VARCHAR     │            0.00 │
├───────────────────────────────┴─────────────┴─────────────────┤
│ 27 rows                                             3 columns │
└───────────────────────────────────────────────────────────────┘

# OpenFEMA Dataset: NFIP Residential Penetration Rates - v1
https://www.fema.gov/openfema-data-page/nfip-residential-penetration-rates-v1

In [21]:
%%time

# URL of the Parquet file to download
url = "https://www.fema.gov/api/open/v1/NfipResidentialPenetrationRates.parquet"

# path of saved file
file_path = "data/NfipResidentialPenetrationRates.parquet"

# send an HTTP GET request to the URL
response = requests.get(url)

# check if the request was successful (status code 200)
if response.status_code == 200:
    
    # write the content of the response to a file
    with open(file_path, 'wb') as file:
        file.write(response.content)
    print("File downloaded successfully.")
    
else:
    print("Failed to download file.")

File downloaded successfully.
CPU times: user 16.2 ms, sys: 5.49 ms, total: 21.7 ms
Wall time: 963 ms

In [22]:
# count rows
duckdb.sql("""
    SELECT count(*) AS count_rows
    FROM read_parquet('data/NfipResidentialPenetrationRates.parquet')
""")

┌────────────┐
│ count_rows │
│   int64    │
├────────────┤
│       3162 │
└────────────┘

In [23]:
# preview first five rows
duckdb.sql("""
    SELECT *
    FROM read_parquet('data/NfipResidentialPenetrationRates.parquet')
    LIMIT 5
""").df()

,state,county,resPenetrationRate,resContractsInForce,totalResStructures,fipsCode,asOfDate,id
0,Alabama,Autauga,0.0114,237,20789,1001,2025-05-15,95f9d9a4-298c-445a-b279-0cfa447d1850
1,Alabama,Baldwin,0.1078,10501,97390,1003,2025-05-15,41afe779-2ce5-43ee-bdd2-1b087261b01a
2,Alabama,Barbour,0.0031,32,10455,1005,2025-05-15,9d25a05c-bda0-4bf5-8e9e-55f712f53c9f
3,Alabama,Bibb,0.0027,21,7693,1007,2025-05-15,a4c74901-8061-4894-ae12-2ce0659888a8
4,Alabama,Blount,0.0018,40,22586,1009,2025-05-15,cb3af383-fb9e-4d7c-8f72-97b98342b871

In [24]:
# preview columns
duckdb.sql("""
    SELECT
        column_name,
        column_type,
        null_percentage
    FROM (SUMMARIZE (FROM read_parquet('data/NfipResidentialPenetrationRates.parquet')))
    ORDER BY null_percentage DESC
""")

┌─────────────────────┬─────────────┬─────────────────┐
│     column_name     │ column_type │ null_percentage │
│       varchar       │   varchar   │  decimal(9,2)   │
├─────────────────────┼─────────────┼─────────────────┤
│ resPenetrationRate  │ DOUBLE      │            6.01 │
│ resContractsInForce │ INTEGER     │            5.44 │
│ totalResStructures  │ INTEGER     │            0.57 │
│ fipsCode            │ VARCHAR     │            0.57 │
│ state               │ VARCHAR     │            0.00 │
│ county              │ VARCHAR     │            0.00 │
│ asOfDate            │ DATE        │            0.00 │
│ id                  │ VARCHAR     │            0.00 │
└─────────────────────┴─────────────┴─────────────────┘

# 2023 NFIP Reinsurance Placement Information
https://www.fema.gov/about/openfema/data-sets/national-flood-insurance-program-nfip-reinsurance-placement-information

In [25]:
%%time

# URL of the Parquet file to download
url = "https://www.fema.gov/sites/default/files/documents/fema_nfip-reinsurance-placement-information_2023.zip"

# path of saved file
file_path = "data/fema_nfip-reinsurance-placement-information_2023.zip"

# send an HTTP GET request to the URL
response = requests.get(url)

# check if the request was successful (status code 200)
if response.status_code == 200:
    
    # write the content of the response to a file
    with open(file_path, 'wb') as file:
        file.write(response.content)
    print("File downloaded successfully.")
    
else:
    print("Failed to download file.")

File downloaded successfully.
CPU times: user 42.8 ms, sys: 18.9 ms, total: 61.7 ms
Wall time: 611 ms

Preview files inside ZIP.

In [26]:
!unzip -l data/fema_nfip-reinsurance-placement-information_2023.zip

Archive:  data/fema_nfip-reinsurance-placement-information_2023.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   288003  09-27-2023 12:55   fema_nfip-reinsurance-placement-information_2023/NFIP_2023_KRSpatialKat_ForMarkets_ControlTotals.pdf
   342686  09-27-2023 12:55   fema_nfip-reinsurance-placement-information_2023/NFIP_2023_KRSpatialKat_InlandFlood_xNATCPrecip_ForMarkets_ResultsSummary.pdf
   350586  09-27-2023 12:55   fema_nfip-reinsurance-placement-information_2023/NFIP_2023_KRSpatialKat_StormSurge_wNATCPrecip_ForMarkets_ResultsSummary.pdf
   388991  09-27-2023 12:55   fema_nfip-reinsurance-placement-information_2023/NFIP_2023_RMSv21_StormSurge_ForMarkets_ControlTotals.pdf
   667614  09-27-2023 12:55   fema_nfip-reinsurance-placement-information_2023/NFIP_2023_RMSv21_StormSurge_ForMarkets_ResultsSummary.pdf
   687022  09-27-2023 12:55   fema_nfip-reinsurance-placement-information_2023/NFIP_2023_VeriskTSv9_InlandFlood_ForMarkets_ResultsSummary.pdf
   685523  09-27-2023 12:55   fema_nfip-reinsurance-placement-information_2023/NFIP_2023_VeriskTSv9_StormSurgewPrecip_ForMarkets_ControlTotals.pdf
   653862  09-27-2023 12:55   fema_nfip-reinsurance-placement-information_2023/NFIP_2023_VeriskTSv9_StormSurgewPrecip_ForMarkets_ResultsSummary.pdf
---------                     -------
  4064287                     8 files

# OpenFEMA Dataset: NFIP Community Layer Comprehensive - v1
https://www.fema.gov/openfema-data-page/nfip-community-layer-comprehensive-v1

In [27]:
%%time

# URL of the Parquet file to download
url = "https://www.fema.gov/api/open/v1/NfipCommunityLayerComprehensive.parquet"

# path of saved file
file_path = "data/NfipCommunityLayerComprehensive.parquet"

# send an HTTP GET request to the URL
response = requests.get(url)

# check if the request was successful (status code 200)
if response.status_code == 200:
    
    # write the content of the response to a file
    with open(file_path, 'wb') as file:
        file.write(response.content)
    print("File downloaded successfully.")
    
else:
    print("Failed to download file.")

File downloaded successfully.
CPU times: user 6.61 s, sys: 1.72 s, total: 8.33 s
Wall time: 2min 21s

In [28]:
# count rows
duckdb.sql("""
    SELECT count(*) AS count_rows
    FROM read_parquet('data/NfipCommunityLayerComprehensive.parquet')
""")

┌────────────┐
│ count_rows │
│   int64    │
├────────────┤
│      51943 │
└────────────┘

In [29]:
# preview first five rows
duckdb.sql("""
    SELECT *
    FROM read_parquet('data/NfipCommunityLayerComprehensive.parquet')
    LIMIT 5
""").df()

,id,communityIdNumber,stateCode,countyCode,censusGeoid,county,communityName,communityNameShort,censusYear,censusPopulationEntire,...,cisSource,geometrySource,alternateGeoid,alternateName,alternateLongName,layerCreationNotes,censusClassCodes,censusFunctionalStatusCodes,layerTypeCode,layerGeometry
0,1,None,32,32013,3244000,Humboldt,None,None,2023,124,...,None,Census Funcstat S,None,McDermitt,McDermitt CDP,None,U1,None,Statistical Area,"{""type"":""MultiPolygon"",""coordinates"":[[[[-117...."
1,2,530297,None,None,None,None,"YAKAMA NATION, CONFEDERATED TRIBES AND BAND OF",YAKAMA NATION,2023,16902,...,PIVOT,NFHL,53077C_530297,"Yakama Nation, CONFEDERATED TRIBES AND BANDS,",None,None,None,None,TRIBE,"{""type"":""MultiPolygon"",""coordinates"":[[[[-120...."
2,3,050184,05,05123,05123,St. Francis,ST. FRANCIS COUNTY *,ST. FRANCIS*,2023,23090,...,PIVOT,Census County,None,St. Francis,St. Francis County,None,H1,A,County,"{""type"":""MultiPolygon"",""coordinates"":[[[[-90.4..."
3,4,400351,40,40059,4009850,Harper,"BUFFALO, TOWN OF",BUFFALO,2023,1039,...,PIVOT,Census Place,None,Buffalo,Buffalo town,None,C1,A,Place,"{""type"":""MultiPolygon"",""coordinates"":[[[[-99.6..."
4,5,450185,45,45087,45087,Union,UNION COUNTY*,UNION*,2023,27244,...,PIVOT,Census County,None,Union,Union County,None,H1,A,County,"{""type"":""MultiPolygon"",""coordinates"":[[[[-81.4..."

In [30]:
# preview columns
duckdb.sql("""
    SELECT
        column_name,
        column_type,
        null_percentage
    FROM (SUMMARIZE (FROM read_parquet('data/NfipCommunityLayerComprehensive.parquet')))
    ORDER BY null_percentage DESC
""")

┌─────────────────────────────┬─────────────┬─────────────────┐
│         column_name         │ column_type │ null_percentage │
│           varchar           │   varchar   │  decimal(9,2)   │
├─────────────────────────────┼─────────────┼─────────────────┤
│ layerCreationNotes          │ VARCHAR     │           87.24 │
│ alternateGeoid              │ VARCHAR     │           83.77 │
│ communityIdNumber           │ VARCHAR     │           29.63 │
│ communityName               │ VARCHAR     │           29.63 │
│ communityNameShort          │ VARCHAR     │           29.63 │
│ cisType                     │ VARCHAR     │           29.63 │
│ cisSource                   │ VARCHAR     │           29.63 │
│ censusFunctionalStatusCodes │ VARCHAR     │           28.70 │
│ censusPopulationEntire      │ INTEGER     │           12.60 │
│ censusHousingUnitsEntire    │ INTEGER     │           12.60 │
│ censusGeoid                 │ VARCHAR     │            3.48 │
│ alternateLongName           │ VARCHAR     │            3.48 │
│ censusClassCodes            │ VARCHAR     │            3.48 │
│ stateCode                   │ VARCHAR     │            1.17 │
│ countyCode                  │ VARCHAR     │            1.17 │
│ county                      │ VARCHAR     │            1.17 │
│ id                          │ INTEGER     │            0.00 │
│ censusYear                  │ SMALLINT    │            0.00 │
│ landAreaEntire              │ DOUBLE      │            0.00 │
│ geometrySource              │ VARCHAR     │            0.00 │
│ alternateName               │ VARCHAR     │            0.00 │
│ layerTypeCode               │ VARCHAR     │            0.00 │
│ layerGeometry               │ VARCHAR     │            0.00 │
├─────────────────────────────┴─────────────┴─────────────────┤
│ 23 rows                                           3 columns │
└─────────────────────────────────────────────────────────────┘

# OpenFEMA Dataset: NFIP Community Layer No Overlaps Split - v1
https://www.fema.gov/openfema-data-page/nfip-community-layer-no-overlaps-split-v1

In [31]:
%%time

# URL of the Parquet file to download
url = "https://www.fema.gov/api/open/v1/NfipCommunityLayerNoOverlapsSplit.parquet"

# path of saved file
file_path = "data/NfipCommunityLayerNoOverlapsSplit.parquet"

# send an HTTP GET request to the URL
response = requests.get(url)

# check if the request was successful (status code 200)
if response.status_code == 200:
    
    # write the content of the response to a file
    with open(file_path, 'wb') as file:
        file.write(response.content)
    print("File downloaded successfully.")
    
else:
    print("Failed to download file.")

File downloaded successfully.
CPU times: user 6.37 s, sys: 1.68 s, total: 8.05 s
Wall time: 3min 8s

In [32]:
# count rows
duckdb.sql("""
    SELECT count(*) AS count_rows
    FROM read_parquet('data/NfipCommunityLayerNoOverlapsSplit.parquet')
""")

┌────────────┐
│ count_rows │
│   int64    │
├────────────┤
│      37918 │
└────────────┘

In [33]:
# preview first five rows
duckdb.sql("""
    SELECT *
    FROM read_parquet('data/NfipCommunityLayerNoOverlapsSplit.parquet')
    LIMIT 5
""").df()

,id,communityIdNumber,stateCode,countyCode,censusGeoid,county,communityName,communityNameShort,censusYear,censusPopulationEntire,...,cisSource,geometrySource,alternateGeoid,alternateName,alternateLongName,layerCreationNotes,censusClassCodes,censusFunctionalStatusCodes,layerTypeCode,layerGeometry
0,1,190053,19,19061,1903160,Dubuque,"ASBURY, CITY OF",ASBURY,2024,5946,...,PIVOT,Census Place,None,Asbury,Asbury city,None,C1,A,Place,"{""type"":""MultiPolygon"",""coordinates"":[[[[-90.8..."
1,2,480206,48,48135,4853388,Ector,"ODESSA, CITY OF",ODESSA,2024,110636,...,PIVOT,Census Place,None,Odessa,Odessa city,None,C1,A,Place (multi-county),"{""type"":""MultiPolygon"",""coordinates"":[[[[-102...."
2,3,040040,04,04013,0412000,Maricopa,"CHANDLER, CITY OF",CHANDLER,2024,276046,...,PIVOT,Census Place,None,Chandler,Chandler city,None,C1,A,Place,"{""type"":""MultiPolygon"",""coordinates"":[[[[-111...."
3,4,010200,01,01121,0174592,Talladega,"TALLADEGA, CITY OF",TALLADEGA,2024,15861,...,PIVOT,Census Place,None,Talladega,Talladega city,None,C1,A,Place,"{""type"":""MultiPolygon"",""coordinates"":[[[[-86.1..."
4,5,400211,40,40113,4065300,Osage,"SAND SPRINGS, CITY OF",SAND SPRINGS,2024,386,...,PIVOT,Census Place,None,Sand Springs,Sand Springs city,None,C1,A,Place (multi-county),"{""type"":""MultiPolygon"",""coordinates"":[[[[-96.2..."

In [34]:
# preview columns
duckdb.sql("""
    SELECT
        column_name,
        column_type,
        null_percentage
    FROM (SUMMARIZE (FROM read_parquet('data/NfipCommunityLayerNoOverlapsSplit.parquet')))
    ORDER BY null_percentage DESC
""")

┌───────────────────────────┬─────────────┬─────────────────┐
│        column_name        │ column_type │ null_percentage │
│          varchar          │   varchar   │  decimal(9,2)   │
├───────────────────────────┼─────────────┼─────────────────┤
│ layerCreationNotes        │ VARCHAR     │           82.52 │
│ alternateGeoid            │ VARCHAR     │           79.35 │
│ censusPopulationEntire    │ INTEGER     │           17.19 │
│ censusHousingUnitsEntire  │ INTEGER     │           17.19 │
│ censusPopulationPunched   │ INTEGER     │           17.19 │
│ censusHousingUnitsPunched │ INTEGER     │           17.19 │
│ communityNameShort        │ VARCHAR     │            5.85 │
│ cisType                   │ VARCHAR     │            5.85 │
│ cisSource                 │ VARCHAR     │            5.85 │
│ communityIdNumber         │ VARCHAR     │            5.84 │
│     ·                     │    ·        │              ·  │
│     ·                     │    ·        │              ·  │
│     ·                     │    ·        │              ·  │
│ stateCode                 │ VARCHAR     │            0.00 │
│ countyCode                │ VARCHAR     │            0.00 │
│ county                    │ VARCHAR     │            0.00 │
│ censusYear                │ SMALLINT    │            0.00 │
│ landAreaEntire            │ DOUBLE      │            0.00 │
│ landArea2D                │ DOUBLE      │            0.00 │
│ geometrySource            │ VARCHAR     │            0.00 │
│ alternateName             │ VARCHAR     │            0.00 │
│ layerTypeCode             │ VARCHAR     │            0.00 │
│ layerGeometry             │ VARCHAR     │            0.00 │
├───────────────────────────┴─────────────┴─────────────────┤
│ 26 rows (20 shown)                              3 columns │
└───────────────────────────────────────────────────────────┘

# OpenFEMA Dataset: NFIP Community Layer No Overlaps Whole - v1
https://www.fema.gov/openfema-data-page/nfip-community-layer-no-overlaps-whole-v1

In [35]:
%%time

# URL of the Parquet file to download
url = "https://www.fema.gov/api/open/v1/NfipCommunityLayerNoOverlapsWhole.parquet"

# path of saved file
file_path = "data/NfipCommunityLayerNoOverlapsWhole.parquet"

# send an HTTP GET request to the URL
response = requests.get(url)

# check if the request was successful (status code 200)
if response.status_code == 200:
    
    # write the content of the response to a file
    with open(file_path, 'wb') as file:
        file.write(response.content)
    print("File downloaded successfully.")
    
else:
    print("Failed to download file.")

File downloaded successfully.
CPU times: user 5.73 s, sys: 1.5 s, total: 7.24 s
Wall time: 2min 46s

In [36]:
# count rows
duckdb.sql("""
    SELECT count(*) AS count_rows
    FROM read_parquet('data/NfipCommunityLayerNoOverlapsWhole.parquet')
""")

┌────────────┐
│ count_rows │
│   int64    │
├────────────┤
│      29898 │
└────────────┘

In [37]:
# preview first five rows
duckdb.sql("""
    SELECT *
    FROM read_parquet('data/NfipCommunityLayerNoOverlapsWhole.parquet')
    LIMIT 5
""").df()

,id,communityIdNumber,stateCode,countyCode,censusGeoid,county,communityName,communityNameShort,censusYear,censusPopulationEntire,...,censusHousingUnitsPunched,landAreaPunched,cisType,cisSource,geometrySource,alternateName,censusClassCodes,censusFunctionalStatusCodes,layerTypeCode,layerGeometry
0,1,120213,12,12099,1239081,Palm Beach,"LAKE WORTH BEACH, CITY OF",LAKE WORTH BEACH,2024,42219,...,17476,17.677492,CITY,PIVOT,Census Place,Lake Worth Beach,C1,A,Place,"{""type"":""MultiPolygon"",""coordinates"":[[[[-80.0..."
1,2,120214,12,12099,1239375,Palm Beach,"LANTANA, TOWN OF",LANTANA,2024,11504,...,5659,7.708114,TOWN,PIVOT,Census Place,Lantana,C1,A,Place,"{""type"":""MultiPolygon"",""coordinates"":[[[[-80.0..."
2,3,120215,12,12099,1242700,Palm Beach,"MANALAPAN, TOWN OF",MANALAPAN,2024,419,...,306,27.319965,TOWN,PIVOT,Census Place,Manalapan,C1,A,Place,"{""type"":""MultiPolygon"",""coordinates"":[[[[-80.0..."
3,4,120216,12,12099,1242900,Palm Beach,"MANGONIA PARK, TOWN OF",MANGONIA PARK,2024,2142,...,750,1.941475,TOWN,PIVOT,Census Place,Mangonia Park,C1,A,Place,"{""type"":""MultiPolygon"",""coordinates"":[[[[-80.0..."
4,5,120217,12,12099,1249600,Palm Beach,"NORTH PALM BEACH, VILLAGE OF",NORTH PALM BEACH,2024,13162,...,8023,13.719528,VILLAGE,PIVOT,Census Place,North Palm Beach,C1,A,Place,"{""type"":""MultiPolygon"",""coordinates"":[[[[-80.0..."

In [38]:
# preview columns
duckdb.sql("""
    SELECT
        column_name,
        column_type,
        null_percentage
    FROM (SUMMARIZE (FROM read_parquet('data/NfipCommunityLayerNoOverlapsWhole.parquet')))
    ORDER BY null_percentage DESC
""")

┌─────────────────────────────┬─────────────┬─────────────────┐
│         column_name         │ column_type │ null_percentage │
│           varchar           │   varchar   │  decimal(9,2)   │
├─────────────────────────────┼─────────────┼─────────────────┤
│ communityNameShort          │ VARCHAR     │            6.85 │
│ cisType                     │ VARCHAR     │            6.85 │
│ cisSource                   │ VARCHAR     │            6.85 │
│ communityIdNumber           │ VARCHAR     │            6.84 │
│ communityName               │ VARCHAR     │            6.84 │
│ censusGeoid                 │ VARCHAR     │            1.85 │
│ censusClassCodes            │ VARCHAR     │            1.85 │
│ censusFunctionalStatusCodes │ VARCHAR     │            1.85 │
│ censusPopulationEntire      │ INTEGER     │            0.26 │
│ censusHousingUnitsEntire    │ INTEGER     │            0.26 │
│ censusPopulationPunched     │ INTEGER     │            0.26 │
│ censusHousingUnitsPunched   │ INTEGER     │            0.26 │
│ id                          │ INTEGER     │            0.00 │
│ stateCode                   │ VARCHAR     │            0.00 │
│ countyCode                  │ VARCHAR     │            0.00 │
│ county                      │ VARCHAR     │            0.00 │
│ censusYear                  │ SMALLINT    │            0.00 │
│ landAreaEntire              │ DOUBLE      │            0.00 │
│ landAreaPunched             │ DOUBLE      │            0.00 │
│ geometrySource              │ VARCHAR     │            0.00 │
│ alternateName               │ VARCHAR     │            0.00 │
│ layerTypeCode               │ VARCHAR     │            0.00 │
│ layerGeometry               │ VARCHAR     │            0.00 │
├─────────────────────────────┴─────────────┴─────────────────┤
│ 23 rows                                           3 columns │
└─────────────────────────────────────────────────────────────┘

# OpenFEMA Dataset: NFIP Community Status Book - v1
https://www.fema.gov/openfema-data-page/nfip-community-status-book-v1

In [39]:
%%time

# URL of the Parquet file to download
url = "https://www.fema.gov/api/open/v1/NfipCommunityStatusBook.parquet"

# path of saved file
file_path = "data/NfipCommunityStatusBook.parquet"

# send an HTTP GET request to the URL
response = requests.get(url)

# check if the request was successful (status code 200)
if response.status_code == 200:
    
    # write the content of the response to a file
    with open(file_path, 'wb') as file:
        file.write(response.content)
    print("File downloaded successfully.")
    
else:
    print("Failed to download file.")

File downloaded successfully.
CPU times: user 38.1 ms, sys: 30.6 ms, total: 68.7 ms
Wall time: 410 ms

In [40]:
# count rows
duckdb.sql("""
    SELECT count(*) AS count_rows
    FROM read_parquet('data/NfipCommunityStatusBook.parquet')
""")

┌────────────┐
│ count_rows │
│   int64    │
├────────────┤
│      25053 │
└────────────┘

In [41]:
# preview first five rows
duckdb.sql("""
    SELECT *
    FROM read_parquet('data/NfipCommunityStatusBook.parquet')
    LIMIT 5
""").df()

,communityIdNumber,communityName,county,state,initialFloodHazardBoundaryMap,initialFloodInsuranceRateMap,currentlyEffectiveMapDate,regularEmergencyProgramDate,tribal,participatingInNFIP,originalEntryDate,classRatingEffectiveDate,classRating,sfhaDiscount,nonSfhaDiscount,lastRefresh
0,230563,"T06 R18 WELS, TOWNSHIP OF",SOMERSET COUNTY,ME,NaT,NaT,(NSFHA),04/30/84,False,True,NaT,NaT,None,None,None,2025-05-14 08:55:53.865
1,010232,"OHATCHEE, TOWN OF",CALHOUN COUNTY,AL,1975-01-31,2007-09-28,03/16/16,08/18/04,False,True,NaT,NaT,None,None,None,2025-05-14 08:54:44.047
2,010233,"CENTRE, CITY OF",CHEROKEE COUNTY,AL,1975-02-07,1980-03-14,03/16/16,03/14/80,False,True,NaT,NaT,None,None,None,2025-05-14 08:54:44.061
3,120275,"GULF BREEZE, CITY OF",SANTA ROSA COUNTY,FL,1974-06-28,1977-09-01,11/19/21,09/01/77,False,True,1993-10-01,2025-04-01,6,20%,10%,2025-05-14 08:55:06.066
4,120308,"EDGEWATER, CITY OF",VOLUSIA COUNTY,FL,1974-08-23,1980-09-03,09/29/17,09/03/80,False,True,1992-10-01,2025-04-01,6,20%,10%,2025-05-14 08:55:06.284

In [42]:
# preview columns
duckdb.sql("""
    SELECT
        column_name,
        column_type,
        null_percentage
    FROM (SUMMARIZE (FROM read_parquet('data/NfipCommunityStatusBook.parquet')))
    ORDER BY null_percentage DESC
""")

┌───────────────────────────────┬─────────────┬─────────────────┐
│          column_name          │ column_type │ null_percentage │
│            varchar            │   varchar   │  decimal(9,2)   │
├───────────────────────────────┼─────────────┼─────────────────┤
│ sfhaDiscount                  │ VARCHAR     │           93.85 │
│ originalEntryDate             │ DATE        │           92.96 │
│ classRatingEffectiveDate      │ DATE        │           92.96 │
│ classRating                   │ VARCHAR     │           92.94 │
│ nonSfhaDiscount               │ VARCHAR     │           92.94 │
│ initialFloodHazardBoundaryMap │ DATE        │           20.08 │
│ initialFloodInsuranceRateMap  │ DATE        │            4.49 │
│ currentlyEffectiveMapDate     │ VARCHAR     │            0.72 │
│ regularEmergencyProgramDate   │ VARCHAR     │            0.01 │
│ communityIdNumber             │ VARCHAR     │            0.00 │
│ communityName                 │ VARCHAR     │            0.00 │
│ county                        │ VARCHAR     │            0.00 │
│ state                         │ VARCHAR     │            0.00 │
│ tribal                        │ BOOLEAN     │            0.00 │
│ participatingInNFIP           │ BOOLEAN     │            0.00 │
│ lastRefresh                   │ TIMESTAMP   │            0.00 │
├───────────────────────────────┴─────────────┴─────────────────┤
│ 16 rows                                             3 columns │
└───────────────────────────────────────────────────────────────┘